# Generated by Django 4.0.3 on 2022-03-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='previews/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
