# Generated by Django 4.0.3 on 2022-03-20 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
